{
 "title": "Grupo9-IoT",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Monitoreo de temperatura",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iotdata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"sensor_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatura Actual",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iotdata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"sensor_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Monitoreo de (Tmax - Tmin) diario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "data = () =>\r\n    from(bucket: \"iotdata\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"device_id\"] == \"sensor_temperature\")\r\n\r\nmin =\r\n    data()\r\n        |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\r\n        |> set(key: \"_field\", value: \"min_Compteur\")\r\n\r\nmax =\r\n    data()\r\n        |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n        |> set(key: \"_field\", value: \"max_Compteur\")\r\n\r\nunion(tables: [min, max])"
    }
   ]
  },
  {
   "title": "Monitoreo de GDD diario",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "data = () =>\r\n    from(bucket: \"iotdata\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"device_id\"] == \"sensor_temperature\")\r\n        |> group(columns: [\"date\"])\r\n\r\nmin =\r\n    data()\r\n        |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\r\n        |> set(key: \"_field\", value: \"min_Compteur\")\r\n\r\nmax =\r\n    data()\r\n        |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n        |> set(key: \"_field\", value: \"max_Compteur\")\r\n\r\nunion(tables: [min, max])\r\n    |> group(columns: [\"Tiempo\"], mode:\"by\")\r\n    |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n    |> map(fn: (r) => ({ r with _value: (r._value / 2.0) - 15.0 }))\r\n"
    }
   ]
  },
  {
   "title": "GDD acumulado",
   "type": "stat",
   "description": "La cantidad de GDD a alcanzar para el tomate es de un valor de 900",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "data = () =>\r\n    from(bucket: \"iotdata\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"device_id\"] == \"sensor_temperature\")\r\n        |> group(columns: [\"date\"])\r\n\r\nmin =\r\n    data()\r\n        |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\r\n        |> set(key: \"_field\", value: \"min_Compteur\")\r\n\r\nmax =\r\n    data()\r\n        |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n        |> set(key: \"_field\", value: \"max_Compteur\")\r\n\r\nunion(tables: [min, max])\r\n    |> group()\r\n    |> sum()\r\n    |> map(fn: (r) => ({ r with _value: r._value / 2.0 }))\r\n    |> map(fn: (r) => ({ r with _value: r._value - 15.0 }))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } }
 ]
}